
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 2, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.fileName0 = QtWidgets.QLabel(self.centralwidget)
        self.fileName0.setObjectName("fileName0")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fileName0)
        self.fileName1 = QtWidgets.QLabel(self.centralwidget)
        self.fileName1.setObjectName("fileName1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fileName1)
        self.fileName2 = QtWidgets.QLabel(self.centralwidget)
        self.fileName2.setObjectName("fileName2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fileName2)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar0 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar0.setProperty("value", 24)
        self.progressBar0.setObjectName("progressBar0")
        self.gridLayout.addWidget(self.progressBar0, 0, 0, 1, 1)
        self.speed0 = QtWidgets.QLabel(self.centralwidget)
        self.speed0.setObjectName("speed0")
        self.gridLayout.addWidget(self.speed0, 0, 1, 1, 1)
        self.progressBar1 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar1.setProperty("value", 24)
        self.progressBar1.setObjectName("progressBar1")
        self.gridLayout.addWidget(self.progressBar1, 1, 0, 1, 1)
        self.speed1 = QtWidgets.QLabel(self.centralwidget)
        self.speed1.setObjectName("speed1")
        self.gridLayout.addWidget(self.speed1, 1, 1, 1, 1)
        self.speed2 = QtWidgets.QLabel(self.centralwidget)
        self.speed2.setObjectName("speed2")
        self.gridLayout.addWidget(self.speed2, 2, 1, 1, 1)
        self.progressBar2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar2.setProperty("value", 24)
        self.progressBar2.setObjectName("progressBar2")
        self.gridLayout.addWidget(self.progressBar2, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "添加下载"))
        self.comboBox.setItemText(0, _translate("MainWindow", "you-get(音频、视频网址)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Aria2(普通文件)"))
        self.pushButton.setText(_translate("MainWindow", "提交"))
        self.label.setText(_translate("MainWindow", "HOST"))
        self.pushButton_2.setText(_translate("MainWindow", "绑定"))
        self.fileName0.setText(_translate("MainWindow", "文件名"))
        self.fileName1.setText(_translate("MainWindow", "文件名"))
        self.fileName2.setText(_translate("MainWindow", "文件名"))
        self.speed0.setText(_translate("MainWindow", "速度"))
        self.speed1.setText(_translate("MainWindow", "速度"))
        self.speed2.setText(_translate("MainWindow", "速度"))
        self.label_8.setText(_translate("MainWindow", "等待下载"))
        self.label_9.setText(_translate("MainWindow", "已完成"))
